# -*- coding: utf-8 -*-
"""algorithm_brute-force.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hka42HrUc51CZHegW25qjb-b_GLVeO6u
"""

class Solution(object):
    def arrangeWords(self, text):

        lists = text.split(" ")
        lists.sort(key=len)

        upper_case = lists[0][0].upper()

        result = ""
        counter = 1

        for sentence in lists:
            if counter < len(lists):
                result += (sentence.lower() + " ")
                counter += 1
            else:
                result += sentence.lower()

        return upper_case + result[1:]